### PR TITLE
Adding Mr_Robot with english description and edit Readme

### PR DESCRIPTION
**Pull request by thomasbnt**
Adding Mr_Robot (with english description)
Adding "_write only in English_" on README.md

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
you've still managed to fail... botname

**Comment by thomasbnt** [comment]
The name is exactly the same as the name of the robot.

**Comment by AlexFlipnote** [comment]
You still failed....
Image

**Comment by thomasbnt** [comment]
It must be the same name in both cases? I did not know it, I do it again and again aha

**Comment by Saederup92** [comment]
*Sad violin playing*

**Comment by thomasbnt** [comment]
Okay, pull request agaaaaaaaiin ! :D 

https://github.com/AlexFlipnote/Discord_Fork/pull/39

**Pull request closed without merging**
